### ISSUE TITLE
librato sink and rates

### ISSUE THREAD

**Issue by hoffoo** [armon/statsite#139]
We are using the librato sink with extended_counters statsite was generating event names that ended in ".rate", and librato was not graphing.  Here is our config:

```ini
use_type_prefix = 1
extended_counters = 1
source_regex = /^([^\.]+)\./
stream_cmd = python /usr/lib/statsite/librato.py /etc/statsite/librato.cfg
```

In the sink when I skip events ending in .rate this goes away and librato accepts the metrics and the sink creates them according to sfx_map. Please let me know if there is something wrong with my config.

Thanks for statsite!

**Comment by mheffner** [comment]
@hoffoo Hi! Can you share a patch of what you changed? I'm pretty sure the Librato sink doesn't support extended counters at the moment, so I'd be interested to see what you changed to get it to work. It'd be great to get extended_counters supported in the sink.

**Comment by hoffoo** [comment]
@mheffner so mine is a crappy hack that looks like this

```diff
diff --git a/sinks/librato.py b/sinks/librato.py
index d6f1315..1bc417e 100644
--- a/sinks/librato.py
+++ b/sinks/librato.py
@@ -157,9 +157,12 @@ class LibratoStore(object):
 
         value = float(value)
         source = self.source
-        istimer = self.timer_re.match(key) != None
         name = self.type_re.match(key).group(2)
 
+        # skip messages with .rate, should probably be .rate$
+        if name.find(".rate") > -1:
+            return
+
         # Match the source regex
         if self.source_re != None:
             m = self.source_re.search(name)
@@ -168,10 +171,7 @@ class LibratoStore(object):
                 name = name[0:m.start(0)] + name[m.end(0):]
 
         subf = None
-        if istimer:
-            name, subf = self.split_timer_metric(name)
-        if subf == None:
-            subf = 'value'
+        name, subf = self.split_timer_metric(name)
 
         # Bail if skipping
         if name == None:
```

**Comment by armon** [comment]
@mheffner Any chance of getting this fixed in the sink so we can close this issue? Thanks!

**Comment by mheffner** [comment]
@armon Yeah, looks like the notification on this slipped by me, I'll try to take a look this week.

**Comment by mheffner** [comment]
@armon Any suggestions on how to differentiate between counters and extended counters in the sink protocol? Given both use the prefix "counts.*", it is difficult to differentiate between a counter named `foo.count` and a counter named `foo` with extended counters enabled.

Any chance the prefix for extended counters could be changed to `extended_counters`? Otherwise, I think I may have to add a config option to the librato sink that turns on handling for extended counters.

**Comment by armon** [comment]
@mheffner I think `extended_counters` does not changes the prefix, it just adds new suffix values. Instead of just the sum, you get the other values, so if should be possible to just check the suffix to determine if extended mode is on

**Comment by mheffner** [comment]
@armon Right, it currently does not change the prefix. I was largely asking should we change it to use a different prefix?

The problem is determining when the suffix is due to the change in counter type vs. being part of the metric name. There's nothing that prevents someone from using ".count" as a suffix on their counter metric name and the added suffixes are not escaped from the metric name.

**Comment by armon** [comment]
@mheffner I see... I think its unlikely that those suffix names are used, since otherwise you'd end up with a double suffix. I would just parse the suffix as is. Otherwise, changing the prefix will break all of the sinks.

**Comment by mheffner** [comment]
@hoffoo Can you give this PR a test: https://github.com/armon/statsite/pull/183

**Comment by hoffoo** [comment]
@mheffner thanks! this works out for me
