### ISSUE TITLE
Sinking tags into opentsdb

### ISSUE THREAD

**Issue by priya23** [armon/statsite#194]
Hi,
I was using opentsdb sink provided using following entry into conf file
**stream_cmd = node sinks/opentsdb.js 10.1.170.158 4242  _t_**
but when i passed tagkey and tagvalue it was not sinking properly into the backend .for example
metricname._t_tag:value|kv if i was passing this it was making metricname.t_tag as metric and no tags were detected .
after parse_tags function in sink it worked as it was not pushing the tag and the value was also not availble inside the function..after change the function should look like this
function parse_tags(metric_name,value) {
    var parts = metric_name.split(".");
    var tags = [];
    var current_tag_name = "";
    for (var i in parts)
    {
        var p = parts[i];
        if (p.indexOf(tagprefix) == 0)
        {
            current_tag_name = p.split(tagprefix)[1];
        tags.push(current_tag_name + "=" + value);
        }
        else if (current_tag_name != "")
        {
            tags.push(current_tag_name + "=" + p);
            current_tag_name = "";
        }
    }
    return tags;
}

Correct me if i am wrong in passing the value if not please make the changes in the code

**Comment by armon** [comment]
Adding @ualtinok, could you please comment?

**Comment by ualtinok** [comment]
I think the problem lies on using a tag prefix which is not specific enough. We moved using influxdb yet when we were using OpenTSDB we were sending metrics as:

`metric_name._t_TAGNAME.TAGVALUE._t_ANOTHERTAGNAME.ANOTHERTAGVALUE `

and 

stream_cmd = node sinks/opentsdb.js host port  **\_t\_**

I don't know if OpenTSDB changed anything since we stopped using it but we were able to get correct tags and values with this configuration

**Comment by armon** [comment]
@priya23 Closing based on input from @ualtinok
